- chaosItemLevel: 1660
  class: souleater
  guildDonation: true
  index: 0
  name: Astariax
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1660
  class: aeromancer
  guildDonation: true
  index: 1
  name: Zephayaya
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1640
  class: sorceress
  guildDonation: true
  index: 2
  name: Zephynz
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1640
  class: gunslinger
  guildDonation: true
  index: 3
  name: Zephyyn
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1600
  class: glaivier
  guildDonation: true
  index: 4
  name: Zephtyr
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1600
  class: artist
  guildDonation: true
  index: 5
  name: Aintnoooway
  unas:
  - hesteraGarden
  - sageTower
  - southKurzan
- chaosItemLevel: 1580
  class: souleater
  guildDonation: true
  index: 6
  name: Nightsedging
  unas:
  - hesteraGarden
  - writersLife
  - bleakNightFog
- chaosItemLevel: 1560
  class: deathblade
  guildDonation: true
  index: 7
  name: Zephyyyn
  unas:
  - lopang
- chaosItemLevel: 1540
  class: reaper
  guildDonation: true
  index: 8
  name: Alzyri
  unas:
  - lopang
- chaosItemLevel: 1540
  class: arcanist
  guildDonation: true
  index: 9
  name: Aryzia
  unas:
  - lopang
- chaosItemLevel: 1540
  class: slayer
  guildDonation: true
  index: 10
  name: Alyzari
  unas:
  - lopang
- chaosItemLevel: 1540
  class: scrapper
  guildDonation: true
  index: 11
  name: Azeph
  unas:
  - lopang
- chaosItemLevel: 1540
  class: shadowhunter
  guildDonation: true
  index: 12
  name: Alzenith
  unas:
  - lopang
