"""
    Make sure you have configured skills for your specific class and skill position:
    'key: keybind of the skill
    'skillType': normal or awakening
    'holdTime': hold for x amount of milliseconds or None
    'castTime': cast time in milliseconds or None
    'directional': if the skill needs to be pointed at a direction where mobs are at
    'position': preset region as shown below

    Layout:
                1       2       3       4
    AWAKENING
                    5       6       7       8


    Normal abilities will cast in the order that they are listed. Planning a rotation is optional but recommended.

"""

SKILL_1_REGION = (738, 869, 15, 15)
SKILL_2_REGION = (777, 869, 15, 15)
SKILL_3_REGION = (816, 869, 15, 15)
SKILL_4_REGION = (855, 869, 15, 15)
SKILL_5_REGION = (759, 907, 15, 15)
SKILL_6_REGION = (797, 907, 15, 15)
SKILL_7_REGION = (835, 907, 15, 15)
SKILL_8_REGION = (873, 907, 15, 15)
SKILL_AWAKENING_REGION = (691, 894, 19, 11)

skills = {
    "aeromancer": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1000,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": 1000,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "sorceress": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "arcana": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "deathblade": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 1700,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "summoner": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 500,
            "position": SKILL_5_REGION,
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": SKILL_7_REGION,
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 1000,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        }
    ],
    "scrapper": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 500,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "artist": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "gunslinger": [
        # shotgun
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        # sniper
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 1000,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        # handgun
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": 2500,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "glaivier": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": False,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": 3000,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "paladin": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 500,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": SKILL_4_REGION,
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": SKILL_7_REGION,
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1200,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "slayer": [
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 4000,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "shadowhunter": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 500,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "souleater": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 500,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": False,
        },
    ],
    "reaper": [
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
    "breaker": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_1_REGION,
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_2_REGION,
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_3_REGION,
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_4_REGION,
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_5_REGION,
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_6_REGION,
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_7_REGION,
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_8_REGION,
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": SKILL_AWAKENING_REGION,
            "directional": True,
        },
    ],
}
