skills = {
    "aeromancer": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1000,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": 1000,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "sorceress": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 1000,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "arcanist": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1000,
            "position": (777, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1000,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "deathblade": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 1700,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "summoner": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 500,
            "position": (759, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": (835, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 1000,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "scrapper": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 500,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "artist": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": 0,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "gunslinger": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 1000,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": 2200,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "glaivier": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": False,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": 3000,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": 3000,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "paladin": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 500,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": (855, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 2000,
            "position": (835, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": 1200,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "slayer": [
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 4000,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "shadowhunter": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": 500,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "souleater": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": 500,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": False,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": 2000,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": False,
        },
    ],
    "reaper": [
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": False,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
    "breaker": [
        {
            "key": "q",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (738, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "w",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (777, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "e",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (816, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "r",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (855, 869, 15, 15),
            "directional": True,
        },
        {
            "key": "a",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (759, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "s",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (797, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "d",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (835, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "f",
            "skillType": "normal",
            "holdTime": None,
            "castTime": None,
            "position": (873, 907, 15, 15),
            "directional": True,
        },
        {
            "key": "v",
            "skillType": "awakening",
            "holdTime": None,
            "castTime": None,
            "position": (691, 894, 19, 11),
            "directional": True,
        },
    ],
}
