aeromancer:
- castTime: null
  directional: true
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: false
  holdTime: 3000
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: 1000
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: 1000
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
arcanist:
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: 1000
  directional: false
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: 1000
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
artist:
- castTime: null
  directional: true
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: 2000
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: 0
  directional: true
  holdTime: 2000
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
breaker:
- castTime: null
  directional: true
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
deathblade:
- castTime: null
  directional: true
  holdTime: 1700
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
glaivier:
- castTime: null
  directional: true
  holdTime: 2000
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: false
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: 2000
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: 2000
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: 3000
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: 3000
  key: v
  position: 9
  skillType: awakening
gunslinger:
- castTime: null
  directional: false
  holdTime: 2000
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: 1000
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: 3000
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: false
  holdTime: 2200
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
paladin:
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: 500
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: 2000
  directional: false
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: 2000
  directional: false
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: 1200
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
reaper:
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
scrapper:
- castTime: null
  directional: true
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: 500
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
shadowhunter:
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: 500
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
slayer:
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: 4000
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
sorceress:
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: 1000
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
souleater:
- castTime: null
  directional: true
  holdTime: 500
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: null
  directional: true
  holdTime: 2000
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: v
  position: 9
  skillType: awakening
summoner:
- castTime: null
  directional: false
  holdTime: null
  key: q
  position: 1
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: w
  position: 2
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: e
  position: 3
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: r
  position: 4
  skillType: normal
- castTime: 500
  directional: false
  holdTime: null
  key: a
  position: 5
  skillType: normal
- castTime: null
  directional: false
  holdTime: null
  key: s
  position: 6
  skillType: normal
- castTime: 2000
  directional: false
  holdTime: null
  key: d
  position: 7
  skillType: normal
- castTime: null
  directional: true
  holdTime: null
  key: f
  position: 8
  skillType: normal
- castTime: 1000
  directional: true
  holdTime: null
  key: v
  position: 9
  skillType: awakening
