characters = [
    {
        "index": 0,
        "class": "souleater",
        "ilvl-endless": 1630,
        "ilvl-aor": 1630,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
    {
        "index": 1,
        "class": "aeromancer",
        "ilvl-endless": 1630,
        "ilvl-aor": 1630,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
        {
        "index": 2,
        "class": "sorceress",
        "ilvl-endless": 1610,
        "ilvl-aor": 1610,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "gunslinger",
        "ilvl-endless": 1600,
        "ilvl-aor": 1600,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "glaivier",
        "ilvl-endless": 1600,
        "ilvl-aor": 1600,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "artist",
        "ilvl-endless": 1600,
        "ilvl-aor": 1600,
        "unas": "leaps hesteraGarden sageTower southKurzan",
        "guildDonation": True,
        "guildSailingWeekly": 8,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "deathblade",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "reaper",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "arcana",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "slayer",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "scrapper",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
    {
        "index": 11,
        "class": "shadowhunter",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "unas": "lopang",
        "guildDonation": True,
        "guildSailingWeekly": 2,
        "rapport": False,
    },
]